function samldecode(r){if(!r)return"";if(Nb.test(r))return r;var e=r;if(Ob.test(r)&&(e=decodeURIComponent(r.replace(/\+/g," ")),Nb.test(e)))return e;try{var o=Qa(e),t=Ka(o);if(Nb.test(t))return t}catch(r){throw Error(Ha())}try{for(var a,n=new tb(o);!n.W;){o=e=r=void 0,t=n;var i=U(t,3);switch(1&i&&(t.W=!0),i>>>=1){case 0:var s=t.input,b=t.l,c=t.a,d=t.b,h=s.length,f=c.length;if(t.w=0,t.j=0,b+1>=h)throw Error("invalid uncompressed block header: LEN");if(o=s[b++]|s[b++]<<8,b+1>=h)throw Error("invalid uncompressed block header: NLEN");if(o===~(e=s[b++]|s[b++]<<8))throw Error("invalid uncompressed block header: length verify");if(b+o>s.length)throw Error("input buffer is broken");switch(t.N){case 0:for(;d+o>c.length;){if(o-=r=f-d,O)c.set(s.subarray(b,b+r),d),d+=r,b+=r;else for(;r--;)c[d++]=s[b++];t.b=d,c=t.o(),d=t.b}break;case 1:for(;d+o>c.length;)c=t.o({Z:2});break;default:throw Error("invalid inflate mode")}if(O)c.set(s.subarray(b,b+o),d),d+=o,b+=o;else for(;o--;)c[d++]=s[b++];t.l=b,t.b=d,t.a=c;break;case 1:t.R(Eb,Hb);break;case 2:Mb(t);break;default:throw Error("unknown BTYPE: "+i)}}a=n.X()}catch(r){throw Error(J("Error doing the decompression."))}if(a=Ka(a))return a;throw Error(J("Unable to decode the encoded SAML message."))}

var p,u=this,v=function(a){return"string"==typeof a},aa=function(){},y=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=
typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},ba=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},A=function(a,b){function c(){}c.prototype=b.prototype;a.da=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ya=function(a,d,c){for(var e=Array(arguments.length-2),g=2;g<arguments.length;g++)e[g-2]=arguments[g];return b.prototype[d].apply(a,e)}};var C=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,C);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};A(C,Error);C.prototype.name="CustomError";var ca=function(a,b){a=a.split("%s");for(var c="",e=a.length-1,d=0;d<e;d++)c+=a[d]+(d<b.length?b[d]:"%s");C.call(this,c+a[e])};A(ca,C);ca.prototype.name="AssertionError";var D=function(a,b,c){if(!a){var e="Assertion failed";if(b){e+=": "+b;var d=Array.prototype.slice.call(arguments,2)}throw new ca(""+e,d||[]);}},da=function(a,b){throw new ca("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var ea=Array.prototype.indexOf?function(a,b){D(null!=a.length);return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(v(a))return v(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},fa=Array.prototype.map?function(a,b){D(null!=a.length);return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,e=Array(c),d=v(a)?a.split(""):a,g=0;g<c;g++)g in d&&(e[g]=b.call(void 0,d[g],g,a));return e},ha=function(a,b){a:{for(var c=a.length,
e=v(a)?a.split(""):a,d=0;d<c;d++)if(d in e&&b.call(void 0,e[d],d,a)){b=d;break a}b=-1}return 0>b?null:v(a)?a.charAt(b):a[b]};var ia=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},F=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)},ja=function(a,b){return a<b?-1:a>b?1:0};var G;a:{var ka=u.navigator;if(ka){var la=ka.userAgent;if(la){G=la;break a}}G=""}var H=function(a){return-1!=G.indexOf(a)};var ma=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};var na=function(){return(H("Chrome")||H("CriOS"))&&!H("Edge")};var oa=function(a){oa[" "](a);return a};oa[" "]=aa;var pa=H("Opera"),I=H("Trident")||H("MSIE"),qa=H("Edge"),ra=H("Gecko")&&!(-1!=G.toLowerCase().indexOf("webkit")&&!H("Edge"))&&!(H("Trident")||H("MSIE"))&&!H("Edge"),sa=-1!=G.toLowerCase().indexOf("webkit")&&!H("Edge"),ta=function(){var a=u.document;return a?a.documentMode:void 0},ua;
a:{var va="",wa=function(){var a=G;if(ra)return/rv:([^\);]+)(\)|;)/.exec(a);if(qa)return/Edge\/([\d\.]+)/.exec(a);if(I)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(sa)return/WebKit\/(\S+)/.exec(a);if(pa)return/(?:Version)[ \/]?(\S+)/.exec(a)}();wa&&(va=wa?wa[1]:"");if(I){var xa=ta();if(null!=xa&&xa>parseFloat(va)){ua=String(xa);break a}}ua=va}var ya=ua,za={},Aa;var Ba=u.document;Aa=Ba&&I?ta()||("CSS1Compat"==Ba.compatMode?parseInt(ya,10):5):void 0;var Ca=Object.freeze||function(a){return a};var Ea=function(){this.ba="";this.ea=Da};Ea.prototype.toString=function(){return"SafeHtml{"+this.ba+"}"};var Da={};var Fa=function(){throw Error("Do not instantiate directly");};Fa.prototype.la=null;Fa.prototype.toString=function(){return this.content};var Ga=function(){Fa.call(this)};A(Ga,Fa);var J=function(a){function b(a){this.content=a}b.prototype=a.prototype;return function(a,e){a=new b(String(a));void 0!==e&&(a.la=e);return a}}(Ga);var Ha=function(){return J("Decoding error. Please enter valid base64 characters.")};var Ia=function(a){return fa(a,function(a){a=a.toString(16);return 1<a.length?a:"0"+a}).join("")},Ja=function(a){for(var b=[],c=0,e=0;e<a.length;e++){var d=a.charCodeAt(e);128>d?b[c++]=d:(2048>d?b[c++]=d>>6|192:(55296==(d&64512)&&e+1<a.length&&56320==(a.charCodeAt(e+1)&64512)?(d=65536+((d&1023)<<10)+(a.charCodeAt(++e)&1023),b[c++]=d>>18|240,b[c++]=d>>12&63|128):b[c++]=d>>12|224,b[c++]=d>>6&63|128),b[c++]=d&63|128)}return b},Ka=function(a){for(var b=[],c=0,e=0;c<a.length;){var d=a[c++];if(128>d)b[e++]=
String.fromCharCode(d);else if(191<d&&224>d){var g=a[c++];b[e++]=String.fromCharCode((d&31)<<6|g&63)}else if(239<d&&365>d){g=a[c++];var f=a[c++],h=a[c++];d=((d&7)<<18|(g&63)<<12|(f&63)<<6|h&63)-65536;b[e++]=String.fromCharCode(55296+(d>>10));b[e++]=String.fromCharCode(56320+(d&1023))}else g=a[c++],f=a[c++],b[e++]=String.fromCharCode((d&15)<<12|(g&63)<<6|f&63)}return b.join("")};var K=null,La=null,Ma=null,Oa=function(a,b){var c=y(a);D("array"==c||"object"==c&&"number"==typeof a.length,"encodeByteArray takes an array as a parameter");Na();b=b?Ma:K;c=[];for(var e=0;e<a.length;e+=3){var d=a[e],g=e+1<a.length,f=g?a[e+1]:0,h=e+2<a.length,l=h?a[e+2]:0,m=d>>2;d=(d&3)<<4|f>>4;f=(f&15)<<2|l>>6;l&=63;h||(l=64,g||(f=64));c.push(b[m],b[d],b[f],b[l])}return c.join("")},Qa=function(a){var b=[];Pa(a,function(a){b.push(a)});return b},Pa=function(a,b){function c(b){for(;e<a.length;){var d=
a.charAt(e++),c=La[d];if(null!=c)return c;if(!/^[\s\xa0]*$/.test(d))throw Error("Unknown base64 encoding at char: "+d);}return b}Na();for(var e=0;;){var d=c(-1),g=c(0),f=c(64),h=c(64);if(64===h&&-1===d)break;b(d<<2|g>>4);64!=f&&(b(g<<4&240|f>>2),64!=h&&b(f<<6&192|h))}},Na=function(){if(!K){K={};La={};Ma={};for(var a=0;65>a;a++)K[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a),La[K[a]]=a,Ma[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(a),
62<=a&&(La["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(a)]=a)}};var Ra=function(){this.v=-1};var L=function(){this.v=64;this.h=Array(4);this.ja=Array(this.v);this.K=this.A=0;this.reset()};A(L,Ra);L.prototype.reset=function(){this.h[0]=1732584193;this.h[1]=4023233417;this.h[2]=2562383102;this.h[3]=271733878;this.K=this.A=0};
var Sa=function(a,b,c){c||(c=0);var e=Array(16);if(v(b))for(var d=0;16>d;++d)e[d]=b.charCodeAt(c++)|b.charCodeAt(c++)<<8|b.charCodeAt(c++)<<16|b.charCodeAt(c++)<<24;else for(d=0;16>d;++d)e[d]=b[c++]|b[c++]<<8|b[c++]<<16|b[c++]<<24;b=a.h[0];c=a.h[1];d=a.h[2];var g=a.h[3];var f=b+(g^c&(d^g))+e[0]+3614090360&4294967295;b=c+(f<<7&4294967295|f>>>25);f=g+(d^b&(c^d))+e[1]+3905402710&4294967295;g=b+(f<<12&4294967295|f>>>20);f=d+(c^g&(b^c))+e[2]+606105819&4294967295;d=g+(f<<17&4294967295|f>>>15);f=c+(b^d&
(g^b))+e[3]+3250441966&4294967295;c=d+(f<<22&4294967295|f>>>10);f=b+(g^c&(d^g))+e[4]+4118548399&4294967295;b=c+(f<<7&4294967295|f>>>25);f=g+(d^b&(c^d))+e[5]+1200080426&4294967295;g=b+(f<<12&4294967295|f>>>20);f=d+(c^g&(b^c))+e[6]+2821735955&4294967295;d=g+(f<<17&4294967295|f>>>15);f=c+(b^d&(g^b))+e[7]+4249261313&4294967295;c=d+(f<<22&4294967295|f>>>10);f=b+(g^c&(d^g))+e[8]+1770035416&4294967295;b=c+(f<<7&4294967295|f>>>25);f=g+(d^b&(c^d))+e[9]+2336552879&4294967295;g=b+(f<<12&4294967295|f>>>20);f=
d+(c^g&(b^c))+e[10]+4294925233&4294967295;d=g+(f<<17&4294967295|f>>>15);f=c+(b^d&(g^b))+e[11]+2304563134&4294967295;c=d+(f<<22&4294967295|f>>>10);f=b+(g^c&(d^g))+e[12]+1804603682&4294967295;b=c+(f<<7&4294967295|f>>>25);f=g+(d^b&(c^d))+e[13]+4254626195&4294967295;g=b+(f<<12&4294967295|f>>>20);f=d+(c^g&(b^c))+e[14]+2792965006&4294967295;d=g+(f<<17&4294967295|f>>>15);f=c+(b^d&(g^b))+e[15]+1236535329&4294967295;c=d+(f<<22&4294967295|f>>>10);f=b+(d^g&(c^d))+e[1]+4129170786&4294967295;b=c+(f<<5&4294967295|
f>>>27);f=g+(c^d&(b^c))+e[6]+3225465664&4294967295;g=b+(f<<9&4294967295|f>>>23);f=d+(b^c&(g^b))+e[11]+643717713&4294967295;d=g+(f<<14&4294967295|f>>>18);f=c+(g^b&(d^g))+e[0]+3921069994&4294967295;c=d+(f<<20&4294967295|f>>>12);f=b+(d^g&(c^d))+e[5]+3593408605&4294967295;b=c+(f<<5&4294967295|f>>>27);f=g+(c^d&(b^c))+e[10]+38016083&4294967295;g=b+(f<<9&4294967295|f>>>23);f=d+(b^c&(g^b))+e[15]+3634488961&4294967295;d=g+(f<<14&4294967295|f>>>18);f=c+(g^b&(d^g))+e[4]+3889429448&4294967295;c=d+(f<<20&4294967295|
f>>>12);f=b+(d^g&(c^d))+e[9]+568446438&4294967295;b=c+(f<<5&4294967295|f>>>27);f=g+(c^d&(b^c))+e[14]+3275163606&4294967295;g=b+(f<<9&4294967295|f>>>23);f=d+(b^c&(g^b))+e[3]+4107603335&4294967295;d=g+(f<<14&4294967295|f>>>18);f=c+(g^b&(d^g))+e[8]+1163531501&4294967295;c=d+(f<<20&4294967295|f>>>12);f=b+(d^g&(c^d))+e[13]+2850285829&4294967295;b=c+(f<<5&4294967295|f>>>27);f=g+(c^d&(b^c))+e[2]+4243563512&4294967295;g=b+(f<<9&4294967295|f>>>23);f=d+(b^c&(g^b))+e[7]+1735328473&4294967295;d=g+(f<<14&4294967295|
f>>>18);f=c+(g^b&(d^g))+e[12]+2368359562&4294967295;c=d+(f<<20&4294967295|f>>>12);f=b+(c^d^g)+e[5]+4294588738&4294967295;b=c+(f<<4&4294967295|f>>>28);f=g+(b^c^d)+e[8]+2272392833&4294967295;g=b+(f<<11&4294967295|f>>>21);f=d+(g^b^c)+e[11]+1839030562&4294967295;d=g+(f<<16&4294967295|f>>>16);f=c+(d^g^b)+e[14]+4259657740&4294967295;c=d+(f<<23&4294967295|f>>>9);f=b+(c^d^g)+e[1]+2763975236&4294967295;b=c+(f<<4&4294967295|f>>>28);f=g+(b^c^d)+e[4]+1272893353&4294967295;g=b+(f<<11&4294967295|f>>>21);f=d+(g^
b^c)+e[7]+4139469664&4294967295;d=g+(f<<16&4294967295|f>>>16);f=c+(d^g^b)+e[10]+3200236656&4294967295;c=d+(f<<23&4294967295|f>>>9);f=b+(c^d^g)+e[13]+681279174&4294967295;b=c+(f<<4&4294967295|f>>>28);f=g+(b^c^d)+e[0]+3936430074&4294967295;g=b+(f<<11&4294967295|f>>>21);f=d+(g^b^c)+e[3]+3572445317&4294967295;d=g+(f<<16&4294967295|f>>>16);f=c+(d^g^b)+e[6]+76029189&4294967295;c=d+(f<<23&4294967295|f>>>9);f=b+(c^d^g)+e[9]+3654602809&4294967295;b=c+(f<<4&4294967295|f>>>28);f=g+(b^c^d)+e[12]+3873151461&4294967295;
g=b+(f<<11&4294967295|f>>>21);f=d+(g^b^c)+e[15]+530742520&4294967295;d=g+(f<<16&4294967295|f>>>16);f=c+(d^g^b)+e[2]+3299628645&4294967295;c=d+(f<<23&4294967295|f>>>9);f=b+(d^(c|~g))+e[0]+4096336452&4294967295;b=c+(f<<6&4294967295|f>>>26);f=g+(c^(b|~d))+e[7]+1126891415&4294967295;g=b+(f<<10&4294967295|f>>>22);f=d+(b^(g|~c))+e[14]+2878612391&4294967295;d=g+(f<<15&4294967295|f>>>17);f=c+(g^(d|~b))+e[5]+4237533241&4294967295;c=d+(f<<21&4294967295|f>>>11);f=b+(d^(c|~g))+e[12]+1700485571&4294967295;b=c+
(f<<6&4294967295|f>>>26);f=g+(c^(b|~d))+e[3]+2399980690&4294967295;g=b+(f<<10&4294967295|f>>>22);f=d+(b^(g|~c))+e[10]+4293915773&4294967295;d=g+(f<<15&4294967295|f>>>17);f=c+(g^(d|~b))+e[1]+2240044497&4294967295;c=d+(f<<21&4294967295|f>>>11);f=b+(d^(c|~g))+e[8]+1873313359&4294967295;b=c+(f<<6&4294967295|f>>>26);f=g+(c^(b|~d))+e[15]+4264355552&4294967295;g=b+(f<<10&4294967295|f>>>22);f=d+(b^(g|~c))+e[6]+2734768916&4294967295;d=g+(f<<15&4294967295|f>>>17);f=c+(g^(d|~b))+e[13]+1309151649&4294967295;
c=d+(f<<21&4294967295|f>>>11);f=b+(d^(c|~g))+e[4]+4149444226&4294967295;b=c+(f<<6&4294967295|f>>>26);f=g+(c^(b|~d))+e[11]+3174756917&4294967295;g=b+(f<<10&4294967295|f>>>22);f=d+(b^(g|~c))+e[2]+718787259&4294967295;d=g+(f<<15&4294967295|f>>>17);f=c+(g^(d|~b))+e[9]+3951481745&4294967295;a.h[0]=a.h[0]+b&4294967295;a.h[1]=a.h[1]+(d+(f<<21&4294967295|f>>>11))&4294967295;a.h[2]=a.h[2]+d&4294967295;a.h[3]=a.h[3]+g&4294967295};
L.prototype.update=function(a,b){void 0===b&&(b=a.length);for(var c=b-this.v,e=this.ja,d=this.A,g=0;g<b;){if(0==d)for(;g<=c;)Sa(this,a,g),g+=this.v;if(v(a))for(;g<b;){if(e[d++]=a.charCodeAt(g++),d==this.v){Sa(this,e);d=0;break}}else for(;g<b;)if(e[d++]=a[g++],d==this.v){Sa(this,e);d=0;break}}this.A=d;this.K+=b};
L.prototype.digest=function(){var a=Array((56>this.A?this.v:2*this.v)-this.A);a[0]=128;for(var b=1;b<a.length-8;++b)a[b]=0;var c=8*this.K;for(b=a.length-8;b<a.length;++b)a[b]=c&255,c/=256;this.update(a);a=Array(16);for(b=c=0;4>b;++b)for(var e=0;32>e;e+=8)a[c++]=this.h[b]>>>e&255;return a};var Ta=function(){this.J=void 0},Va=function(a,b){var c=[];Ua(a,b,c);return c.join("")},Ua=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if("array"==y(b)){var e=b;b=e.length;c.push("[");for(var d="",g=0;g<b;g++)c.push(d),d=e[g],Ua(a,a.J?a.J.call(e,String(g),d):d,c),d=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");g="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(d=b[e],"function"!=typeof d&&
(c.push(g),Wa(e,c),c.push(":"),Ua(a,a.J?a.J.call(b,e,d):d,c),g=","));c.push("}");return}}switch(typeof b){case "string":Wa(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}},Xa={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Ya=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g,
Wa=function(a,b){b.push('"',a.replace(Ya,function(a){var b=Xa[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Xa[a]=b);return b}),'"')};var Za=function(a,b){var c=Array.prototype.slice.call(arguments),e=c.shift();if("undefined"==typeof e)throw Error("[goog.string.format] Template required");return e.replace(/%([0\- \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,e,h,l,m,n,r){if("%"==m)return"%";var d=c.shift();if("undefined"==typeof d)throw Error("[goog.string.format] Not enough arguments");arguments[0]=d;return M[m].apply(null,arguments)})},M={s:function(a,b,c){return isNaN(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+
F(" ",Number(c)-a.length):F(" ",Number(c)-a.length)+a},f:function(a,b,c,e,d){e=a.toString();isNaN(d)||""==d||(e=parseFloat(a).toFixed(d));var g=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(e=g+e);if(isNaN(c)||e.length>=Number(c))return e;e=isNaN(d)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(d);a=Number(c)-e.length-g.length;return e=0<=b.indexOf("-",0)?g+e+F(" ",a):g+F(0<=b.indexOf("0",0)?"0":" ",a)+e},d:function(a,b,c,e,d,g,f,h){return M.f(parseInt(a,
10),b,c,e,0,g,f,h)}};M.i=M.d;M.u=M.d;var $a=function(){this.c=new N;this.T=new Ta};$a.prototype.format=function(a){a:if(null!=a){if(v(a)){if(/^[\s\xa0]*$/.test(a)){a=[];break a}a=JSON.parse(a)}var b=[];ab(this,a,b,0);a=b}else a=[];var c="";for(b=0;b<a.length;b++){var e=a[b];e instanceof Ea&&(e instanceof Ea&&e.constructor===Ea&&e.ea===Da?e=e.ba:(da("expected object of type SafeHtml, got '"+e+"' of type "+y(e)),e="type_error:SafeHtml"));c+=e}return c};
var ab=function(a,b,c,e){var d=y(b);switch(d){case "null":case "boolean":case "number":case "string":b=Va(a.T,b);c.push(bb(a.c,b,d));break;case "array":c.push(a.c.ha);for(d=0;d<b.length;d++)0<d&&c.push(a.c.ca),c.push(a.c.H),c.push(F(a.c.D,e+a.c.G)),ab(a,b[d],c,e+a.c.G);0<d&&(c.push(a.c.H),c.push(F(a.c.D,e)));c.push(a.c.ga);break;case "object":c.push(a.c.sa);d=0;for(var g in b)b.hasOwnProperty(g)&&(0<d&&c.push(a.c.ca),c.push(a.c.H),c.push(F(a.c.D,e+a.c.G)),c.push(cb(a.c,Va(a.T,g))),c.push(a.c.qa,a.c.D),
ab(a,b[g],c,e+a.c.G),d++);0<d&&(c.push(a.c.H),c.push(F(a.c.D,e)));c.push(a.c.ra);break;default:b=Va(a.T,""),c.push(bb(a.c,b,"unknown"))}},N=function(){};p=N.prototype;p.D=" ";p.H="\n";p.sa="{";p.ra="}";p.ha="[";p.ga="]";p.ca=",";p.qa=":";p.wa="";p.ua="";var cb=function(a,b){return a.wa+b+a.ua};N.prototype.xa="";N.prototype.va="";var bb=function(a,b,c){return Za(a.xa,c)+b+a.va};N.prototype.G=2;/*


 JavaScript Zlib and Deflate Library

 The MIT License

 Copyright (c) 2011 imaya

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
*/
var O="undefined"!==typeof Uint8Array&&"undefined"!==typeof Uint16Array&&"undefined"!==typeof Uint32Array;var P=function(a,b){this.index="number"===typeof b?b:0;this.F=0;this.buffer=a instanceof(O?Uint8Array:Array)?a:new (O?Uint8Array:Array)(32768);if(2*this.buffer.length<=this.index)throw Error("invalid index");this.buffer.length<=this.index&&this.o()};P.prototype.o=function(){var a=this.buffer,b,c=a.length,e=new (O?Uint8Array:Array)(c<<1);if(O)e.set(a);else for(b=0;b<c;++b)e[b]=a[b];return this.buffer=e};
P.prototype.g=function(a,b,c){var e=this.buffer,d=this.index,g=this.F,f=e[d];c&&1<b&&(a=8<b?(Q[a&255]<<24|Q[a>>>8&255]<<16|Q[a>>>16&255]<<8|Q[a>>>24&255])>>32-b:Q[a]>>8-b);if(8>b+g)f=f<<b|a,g+=b;else for(c=0;c<b;++c)f=f<<1|a>>b-c-1&1,8===++g&&(g=0,e[d++]=Q[f],f=0,d===e.length&&(e=this.o()));e[d]=f;this.buffer=e;this.F=g;this.index=d};P.prototype.finish=function(){var a=this.buffer,b=this.index;0<this.F&&(a[b]<<=8-this.F,a[b]=Q[a[b]],b++);O?a=a.subarray(0,b):a.length=b;return a};
var db=new (O?Uint8Array:Array)(256),R;for(R=0;256>R;++R){var eb=R,fb=eb,gb=7;for(eb>>>=1;eb;eb>>>=1)fb<<=1,fb|=eb&1,--gb;db[R]=(fb<<gb&255)>>>0}var Q=db;/*


 zlib.heap.js

 The MIT License

 Copyright (c) 2011 imaya

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
*/
var hb=function(){this.buffer=new (O?Uint16Array:Array)(1144);this.length=0};hb.prototype.getParent=function(a){return 2*((a-2)/4|0)};hb.prototype.push=function(a,b){var c=this.buffer;var e=this.length;c[this.length++]=b;for(c[this.length++]=a;0<e;)if(a=this.getParent(e),c[e]>c[a])b=c[e],c[e]=c[a],c[a]=b,b=c[e+1],c[e+1]=c[a+1],c[a+1]=b,e=a;else break;return this.length};
hb.prototype.pop=function(){var a=this.buffer,b;var c=a[0];var e=a[1];this.length-=2;a[0]=a[this.length];a[1]=a[this.length+1];for(b=0;;){var d=2*b+2;if(d>=this.length)break;d+2<this.length&&a[d+2]>a[d]&&(d+=2);if(a[d]>a[b]){var g=a[b];a[b]=a[d];a[d]=g;g=a[b+1];a[b+1]=a[d+1];a[d+1]=g}else break;b=d}return{index:e,value:c,length:this.length}};var ib=function(a){var b={P:1};this.P=2;this.$=0;this.input=O&&a instanceof Array?new Uint8Array(a):a;this.b=0;b&&(b.lazy&&(this.$=b.lazy),"number"===typeof b.compressionType&&(this.P=b.compressionType),b.outputBuffer&&(this.a=O&&b.outputBuffer instanceof Array?new Uint8Array(b.outputBuffer):b.outputBuffer),"number"===typeof b.outputIndex&&(this.b=b.outputIndex));this.a||(this.a=new (O?Uint8Array:Array)(32768))},jb=[],S;
for(S=0;288>S;S++)switch(!0){case 143>=S:jb.push([S+48,8]);break;case 255>=S:jb.push([S-144+400,9]);break;case 279>=S:jb.push([S-256,7]);break;case 287>=S:jb.push([S-280+192,8]);break;default:throw Error("invalid literal: "+S);}
var kb=function(a,b){this.length=a;this.ia=b},lb,mb=function(){function a(a){switch(!0){case 3===a:return[257,a-3,0];case 4===a:return[258,a-4,0];case 5===a:return[259,a-5,0];case 6===a:return[260,a-6,0];case 7===a:return[261,a-7,0];case 8===a:return[262,a-8,0];case 9===a:return[263,a-9,0];case 10===a:return[264,a-10,0];case 12>=a:return[265,a-11,1];case 14>=a:return[266,a-13,1];case 16>=a:return[267,a-15,1];case 18>=a:return[268,a-17,1];case 22>=a:return[269,a-19,2];case 26>=a:return[270,a-23,2];
case 30>=a:return[271,a-27,2];case 34>=a:return[272,a-31,2];case 42>=a:return[273,a-35,3];case 50>=a:return[274,a-43,3];case 58>=a:return[275,a-51,3];case 66>=a:return[276,a-59,3];case 82>=a:return[277,a-67,4];case 98>=a:return[278,a-83,4];case 114>=a:return[279,a-99,4];case 130>=a:return[280,a-115,4];case 162>=a:return[281,a-131,5];case 194>=a:return[282,a-163,5];case 226>=a:return[283,a-195,5];case 257>=a:return[284,a-227,5];case 258===a:return[285,a-258,0];default:throw Error("invalid length: "+
a);}}var b=[],c;for(c=3;258>=c;c++){var e=a(c);b[c]=e[2]<<24|e[1]<<16|e[0]}return b}();lb=O?new Uint32Array(mb):mb;
var ob=function(a,b){function c(a,b){var c=a.ia,d=[],e=0;var f=lb[a.length];d[e++]=f&65535;d[e++]=f>>16&255;d[e++]=f>>24;switch(!0){case 1===c:c=[0,c-1,0];break;case 2===c:c=[1,c-2,0];break;case 3===c:c=[2,c-3,0];break;case 4===c:c=[3,c-4,0];break;case 6>=c:c=[4,c-5,1];break;case 8>=c:c=[5,c-7,1];break;case 12>=c:c=[6,c-9,2];break;case 16>=c:c=[7,c-13,2];break;case 24>=c:c=[8,c-17,3];break;case 32>=c:c=[9,c-25,3];break;case 48>=c:c=[10,c-33,4];break;case 64>=c:c=[11,c-49,4];break;case 96>=c:c=[12,
c-65,5];break;case 128>=c:c=[13,c-97,5];break;case 192>=c:c=[14,c-129,6];break;case 256>=c:c=[15,c-193,6];break;case 384>=c:c=[16,c-257,7];break;case 512>=c:c=[17,c-385,7];break;case 768>=c:c=[18,c-513,8];break;case 1024>=c:c=[19,c-769,8];break;case 1536>=c:c=[20,c-1025,9];break;case 2048>=c:c=[21,c-1537,9];break;case 3072>=c:c=[22,c-2049,10];break;case 4096>=c:c=[23,c-3073,10];break;case 6144>=c:c=[24,c-4097,11];break;case 8192>=c:c=[25,c-6145,11];break;case 12288>=c:c=[26,c-8193,12];break;case 16384>=
c:c=[27,c-12289,12];break;case 24576>=c:c=[28,c-16385,13];break;case 32768>=c:c=[29,c-24577,13];break;default:throw Error("invalid distance");}f=c;d[e++]=f[0];d[e++]=f[1];d[e++]=f[2];e=0;for(c=d.length;e<c;++e)m[n++]=d[e];k[d[0]]++;q[d[3]]++;r=a.length+b-1;l=null}var e,d,g,f,h={},l,m=O?new Uint16Array(2*b.length):[],n=0,r=0,k=new (O?Uint32Array:Array)(286),q=new (O?Uint32Array:Array)(30),E=a.$;if(!O){for(d=0;285>=d;)k[d++]=0;for(d=0;29>=d;)q[d++]=0}k[256]=1;var t=0;for(e=b.length;t<e;++t){d=f=0;for(g=
3;d<g&&t+d!==e;++d)f=f<<8|b[t+d];void 0===h[f]&&(h[f]=[]);d=h[f];if(!(0<r--)){for(;0<d.length&&32768<t-d[0];)d.shift();if(t+3>=e){l&&c(l,-1);d=0;for(g=e-t;d<g;++d)f=b[t+d],m[n++]=f,++k[f];break}0<d.length?(g=nb(b,t,d),l?l.length<g.length?(f=b[t-1],m[n++]=f,++k[f],c(g,0)):c(l,-1):g.length<E?l=g:c(g,0)):l?c(l,-1):(f=b[t],m[n++]=f,++k[f])}d.push(t)}m[n++]=256;k[256]++;a.pa=k;a.oa=q;return O?m.subarray(0,n):m},nb=function(a,b,c){var e=0,d=a.length;var g=0;var f=c.length;a:for(;g<f;g++){var h=c[f-g-1];
var l=3;if(3<e){for(l=e;3<l;l--)if(a[h+l-1]!==a[b+l-1])continue a;l=e}for(;258>l&&b+l<d&&a[h+l]===a[b+l];)++l;if(l>e){var m=h;e=l}if(258===l)break}return new kb(e,b-m)},qb=function(a,b){var c=a.length,e=new hb,d=new (O?Uint8Array:Array)(c),g;if(!O)for(g=0;g<c;g++)d[g]=0;for(g=0;g<c;++g)0<a[g]&&e.push(g,a[g]);a=Array(e.length/2);var f=new (O?Uint32Array:Array)(e.length/2);if(1===a.length)return d[e.pop().index]=1,d;g=0;for(c=e.length/2;g<c;++g)a[g]=e.pop(),f[g]=a[g].value;b=pb(f,f.length,b);g=0;for(c=
a.length;g<c;++g)d[a[g].index]=b[g];return d},pb=function(a,b,c){function e(a){var c=l[a][m[a]];c===b?(e(a+1),e(a+1)):--f[c];++m[a]}var d=new (O?Uint16Array:Array)(c),g=new (O?Uint8Array:Array)(c),f=new (O?Uint8Array:Array)(b),h=Array(c),l=Array(c),m=Array(c),n=(1<<c)-b,r=1<<c-1,k;d[c-1]=b;for(k=0;k<c;++k)n<r?g[k]=0:(g[k]=1,n-=r),n<<=1,d[c-2-k]=(d[c-1-k]/2|0)+b;d[0]=g[0];h[0]=Array(d[0]);l[0]=Array(d[0]);for(k=1;k<c;++k)d[k]>2*d[k-1]+g[k]&&(d[k]=2*d[k-1]+g[k]),h[k]=Array(d[k]),l[k]=Array(d[k]);for(n=
0;n<b;++n)f[n]=c;for(r=0;r<d[c-1];++r)h[c-1][r]=a[r],l[c-1][r]=r;for(n=0;n<c;++n)m[n]=0;1===g[c-1]&&(--f[0],++m[c-1]);for(k=c-2;0<=k;--k){c=n=0;var q=m[k+1];for(r=0;r<d[k];r++)c=h[k+1][q]+h[k+1][q+1],c>a[n]?(h[k][r]=c,l[k][r]=b,q+=2):(h[k][r]=a[n],l[k][r]=n,++n);m[k]=0;1===g[k]&&e(k)}return f},rb=function(a){var b=new (O?Uint16Array:Array)(a.length),c=[],e=[],d=0,g,f;var h=0;for(g=a.length;h<g;h++)c[a[h]]=(c[a[h]]|0)+1;h=1;for(g=16;h<=g;h++)e[h]=d,d+=c[h]|0,d<<=1;h=0;for(g=a.length;h<g;h++)for(d=
e[a[h]],e[a[h]]+=1,c=b[h]=0,f=a[h];c<f;c++)b[h]=b[h]<<1|d&1,d>>>=1;return b};/*


 JavaScript Inflate Library

 The MIT License

 Copyright (c) 2012 imaya

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
*/
var sb=function(a){var b=a.length,c=0,e=Number.POSITIVE_INFINITY,d,g,f;for(g=0;g<b;++g)a[g]>c&&(c=a[g]),a[g]<e&&(e=a[g]);var h=1<<c;var l=new (O?Uint32Array:Array)(h);var m=1;var n=0;for(d=2;m<=c;){for(g=0;g<b;++g)if(a[g]===m){var r=0;var k=n;for(f=0;f<m;++f)r=r<<1|k&1,k>>=1;k=m<<16|g;for(f=r;f<h;f+=d)l[f]=k;++n}++m;n<<=1;d<<=1}return[l,c,e]};var tb=function(a){var b;this.M=[];this.bufferSize=32768;this.j=this.w=this.l=this.V=0;this.input=O?new Uint8Array(a):a;this.W=!1;this.N=1;this.resize=!1;if(b||!(b={}))b.index&&(this.l=b.index),b.bufferSize&&(this.bufferSize=b.bufferSize),b.bufferType&&(this.N=b.bufferType),b.resize&&(this.resize=b.resize);switch(this.N){case 0:this.b=32768;this.a=new (O?Uint8Array:Array)(32768+this.bufferSize+258);break;case 1:this.b=0;this.a=new (O?Uint8Array:Array)(this.bufferSize);this.o=this.na;this.X=this.ka;
this.R=this.ma;break;default:throw Error("invalid inflate mode");}},ub,vb=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15];ub=O?new Uint16Array(vb):vb;var wb,xb=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258,258,258];wb=O?new Uint16Array(xb):xb;var yb,zb=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0,0,0];yb=O?new Uint8Array(zb):zb;
var Ab,Bb=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577];Ab=O?new Uint16Array(Bb):Bb;var Cb,Db=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13];Cb=O?new Uint8Array(Db):Db;var Eb,Fb=new (O?Uint8Array:Array)(288),T,Gb;T=0;for(Gb=Fb.length;T<Gb;++T)Fb[T]=143>=T?8:255>=T?9:279>=T?7:8;Eb=sb(Fb);var Hb,Ib=new (O?Uint8Array:Array)(30),Jb,Kb;Jb=0;for(Kb=Ib.length;Jb<Kb;++Jb)Ib[Jb]=5;Hb=sb(Ib);
var U=function(a,b){for(var c=a.w,e=a.j,d=a.input,g=a.l,f=d.length;e<b;){if(g>=f)throw Error("input buffer is broken");c|=d[g++]<<e;e+=8}a.w=c>>>b;a.j=e-b;a.l=g;return c&(1<<b)-1},Lb=function(a,b){var c=a.w,e=a.j,d=a.input,g=a.l,f=d.length,h=b[0];for(b=b[1];e<b&&!(g>=f);)c|=d[g++]<<e,e+=8;d=h[c&(1<<b)-1];f=d>>>16;a.w=c>>f;a.j=e-f;a.l=g;return d&65535},Mb=function(a){function b(a,b,c){var d=this.aa,e;for(e=0;e<a;){var f=Lb(this,b);switch(f){case 16:for(f=3+U(this,2);f--;)c[e++]=d;break;case 17:for(f=
3+U(this,3);f--;)c[e++]=0;d=0;break;case 18:for(f=11+U(this,7);f--;)c[e++]=0;d=0;break;default:d=c[e++]=f}}this.aa=d;return c}var c=U(a,5)+257,e=U(a,5)+1,d=U(a,4)+4,g=new (O?Uint8Array:Array)(ub.length),f;for(f=0;f<d;++f)g[ub[f]]=U(a,3);if(!O)for(f=d,d=g.length;f<d;++f)g[ub[f]]=0;d=sb(g);g=new (O?Uint8Array:Array)(c);f=new (O?Uint8Array:Array)(e);a.aa=0;a.R(sb(b.call(a,c,d,g)),sb(b.call(a,e,d,f)))};p=tb.prototype;
p.R=function(a,b){var c=this.a,e=this.b;this.Y=a;for(var d=c.length-258,g,f,h;256!==(g=Lb(this,a));)if(256>g)e>=d&&(this.b=e,c=this.o(),e=this.b),c[e++]=g;else for(g-=257,h=wb[g],0<yb[g]&&(h+=U(this,yb[g])),g=Lb(this,b),f=Ab[g],0<Cb[g]&&(f+=U(this,Cb[g])),e>=d&&(this.b=e,c=this.o(),e=this.b);h--;)c[e]=c[e++-f];for(;8<=this.j;)this.j-=8,this.l--;this.b=e};
p.ma=function(a,b){var c=this.a,e=this.b;this.Y=a;for(var d=c.length,g,f,h;256!==(g=Lb(this,a));)if(256>g)e>=d&&(c=this.o(),d=c.length),c[e++]=g;else for(g-=257,h=wb[g],0<yb[g]&&(h+=U(this,yb[g])),g=Lb(this,b),f=Ab[g],0<Cb[g]&&(f+=U(this,Cb[g])),e+h>d&&(c=this.o(),d=c.length);h--;)c[e]=c[e++-f];for(;8<=this.j;)this.j-=8,this.l--;this.b=e};
p.o=function(){var a=new (O?Uint8Array:Array)(this.b-32768),b=this.b-32768,c,e=this.a;if(O)a.set(e.subarray(32768,a.length));else{var d=0;for(c=a.length;d<c;++d)a[d]=e[d+32768]}this.M.push(a);this.V+=a.length;if(O)e.set(e.subarray(b,b+32768));else for(d=0;32768>d;++d)e[d]=e[b+d];this.b=32768;return e};
p.na=function(a){var b=this.input.length/this.l+1|0,c=this.input,e=this.a;a&&("number"===typeof a.Z&&(b=a.Z),"number"===typeof a.fa&&(b+=a.fa));2>b?(a=(c.length-this.l)/this.Y[2],a=a/2*258|0,a=a<e.length?e.length+a:e.length<<1):a=e.length*b;O?(a=new Uint8Array(a),a.set(e)):a=e;return this.a=a};
p.X=function(){var a=0,b=this.a,c=this.M,e=new (O?Uint8Array:Array)(this.V+(this.b-32768)),d,g;if(0===c.length)return O?this.a.subarray(32768,this.b):this.a.slice(32768,this.b);var f=0;for(d=c.length;f<d;++f){var h=c[f];var l=0;for(g=h.length;l<g;++l)e[a++]=h[l]}f=32768;for(d=this.b;f<d;++f)e[a++]=b[f];this.M=[];return this.buffer=e};
p.ka=function(){var a=this.b;if(O)if(this.resize){var b=new Uint8Array(a);b.set(this.a.subarray(0,a))}else b=this.a.subarray(0,a);else this.a.length>a&&(this.a.length=a),b=this.a;return this.buffer=b};/*


 zlib.js
 JavaScript Zlib and Deflate Library

 The MIT License

 Copyright (c) 2011 imaya

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
*/
var Nb=/(<.+>)+/,Ob=/%[0-9a-fA-F]{2}/;var Pb=!I&&!(H("Safari")&&!(na()||H("Coast")||H("Opera")||H("Edge")||H("Silk")||H("Android"))),Qb=function(a){if(/-[a-z]/.test("command"))return null;if(Pb&&a.dataset){if(!(!H("Android")||na()||H("Firefox")||H("Opera")||H("Silk")||"command"in a.dataset))return null;a=a.dataset.command;return void 0===a?null:a}return a.getAttribute("data-"+"command".replace(/([A-Z])/g,"-$1").toLowerCase())};var Rb=function(a){var b=document;return v(a)?b.getElementById(a):a},Sb=function(){var a=Rb("enc-dec-form"),b=a||document;if(b.querySelectorAll&&b.querySelector)a=b.querySelectorAll(".enc-dec-command");else{var c;b=document;a=a||b;if(a.querySelectorAll&&a.querySelector)a=a.querySelectorAll(".enc-dec-command");else if(a.getElementsByClassName){var e=a.getElementsByClassName("enc-dec-command");a=e}else{e=a.getElementsByTagName("*");var d={};for(b=c=0;a=e[b];b++){var g=a.className,f;if(f="function"==
typeof g.split)f=0<=ea(g.split(/\s+/),"enc-dec-command");f&&(d[c++]=a)}d.length=c;a=d}}return a},Tb=function(a,b){D(null!=a,"goog.dom.setTextContent expects a non-null value for node");if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else{for(var c;c=a.firstChild;)a.removeChild(c);D(a,"Node cannot be null or undefined.");a.appendChild((9==
a.nodeType?a:a.ownerDocument||a.document).createTextNode(String(b)))}};var Ub;(Ub=!I)||(Ub=9<=Number(Aa));var Vb=Ub,Wb;
if(Wb=I){var Xb;if(Object.prototype.hasOwnProperty.call(za,"9"))Xb=za["9"];else{for(var Yb=0,Zb=ia(String(ya)).split("."),$b=ia("9").split("."),ac=Math.max(Zb.length,$b.length),bc=0;0==Yb&&bc<ac;bc++){var cc=Zb[bc]||"",dc=$b[bc]||"";do{var V=/(\d*)(\D*)(.*)/.exec(cc)||["","","",""],W=/(\d*)(\D*)(.*)/.exec(dc)||["","","",""];if(0==V[0].length&&0==W[0].length)break;Yb=ja(0==V[1].length?0:parseInt(V[1],10),0==W[1].length?0:parseInt(W[1],10))||ja(0==V[2].length,0==W[2].length)||ja(V[2],W[2]);cc=V[3];
dc=W[3]}while(0==Yb)}Xb=za["9"]=0<=Yb}Wb=!Xb}var ec=Wb,fc=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});u.addEventListener("test",aa,b);u.removeEventListener("test",aa,b);return a}();var gc=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.U=!1};gc.prototype.stopPropagation=function(){this.U=!0};gc.prototype.preventDefault=function(){this.defaultPrevented=!0};var X=function(a,b){gc.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.B=null;if(a){var c=this.type=a.type,e=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;if(b=a.relatedTarget){if(ra){a:{try{oa(b.nodeName);
var d=!0;break a}catch(g){}d=!1}d||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;null===e?(this.offsetX=sa||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=sa||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==e.clientX?e.clientX:e.pageX,this.clientY=void 0!==e.clientY?e.clientY:e.pageY,
this.screenX=e.screenX||0,this.screenY=e.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=v(a.pointerType)?a.pointerType:hc[a.pointerType]||"";this.state=a.state;this.B=a;a.defaultPrevented&&this.preventDefault()}};A(X,gc);var hc=Ca({2:"touch",3:"pen",4:"mouse"});
X.prototype.stopPropagation=function(){X.da.stopPropagation.call(this);this.B.stopPropagation?this.B.stopPropagation():this.B.cancelBubble=!0};X.prototype.preventDefault=function(){X.da.preventDefault.call(this);var a=this.B;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,ec)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var ic="closure_listenable_"+(1E6*Math.random()|0),jc=0;var kc=function(a,b,c,e,d){this.listener=a;this.I=null;this.src=b;this.type=c;this.capture=!!e;this.S=d;this.key=++jc;this.C=this.O=!1},lc=function(a){a.C=!0;a.listener=null;a.I=null;a.src=null;a.S=null};var mc=function(a){this.src=a;this.m={};this.L=0};mc.prototype.add=function(a,b,c,e,d){var g=a.toString();a=this.m[g];a||(a=this.m[g]=[],this.L++);var f=nc(a,b,e,d);-1<f?(b=a[f],c||(b.O=!1)):(b=new kc(b,this.src,g,!!e,d),b.O=c,a.push(b));return b};mc.prototype.remove=function(a,b,c,e){a=a.toString();if(!(a in this.m))return!1;var d=this.m[a];b=nc(d,b,c,e);return-1<b?(lc(d[b]),D(null!=d.length),Array.prototype.splice.call(d,b,1),0==d.length&&(delete this.m[a],this.L--),!0):!1};
mc.prototype.hasListener=function(a,b){var c=void 0!==a,e=c?a.toString():"",d=void 0!==b;return ma(this.m,function(a){for(var f=0;f<a.length;++f)if(!(c&&a[f].type!=e||d&&a[f].capture!=b))return!0;return!1})};var nc=function(a,b,c,e){for(var d=0;d<a.length;++d){var g=a[d];if(!g.C&&g.listener==b&&g.capture==!!c&&g.S==e)return d}return-1};var oc="closure_lm_"+(1E6*Math.random()|0),pc={},qc=0,sc=function(a,b,c,e,d){if(e&&e.once)rc(a,b,c,e,d);else if("array"==y(b))for(var g=0;g<b.length;g++)sc(a,b[g],c,e,d);else c=tc(c),a&&a[ic]?a.za(b,c,ba(e)?!!e.capture:!!e,d):uc(a,b,c,!1,e,d)},uc=function(a,b,c,e,d,g){if(!b)throw Error("Invalid event type");var f=ba(d)?!!d.capture:!!d,h=vc(a);h||(a[oc]=h=new mc(a));c=h.add(b,c,e,f,g);if(!c.I){e=wc();c.I=e;e.src=a;e.listener=c;if(a.addEventListener)fc||(d=f),void 0===d&&(d=!1),a.addEventListener(b.toString(),
e,d);else if(a.attachEvent)a.attachEvent(xc(b.toString()),e);else if(a.addListener&&a.removeListener)D("change"===b,"MediaQueryList only has a change event"),a.addListener(e);else throw Error("addEventListener and attachEvent are unavailable.");qc++}},wc=function(){var a=yc,b=Vb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},rc=function(a,b,c,e,d){if("array"==y(b))for(var g=0;g<b.length;g++)rc(a,b[g],c,e,d);else c=tc(c),a&&a[ic]?a.Aa(b,
c,ba(e)?!!e.capture:!!e,d):uc(a,b,c,!0,e,d)},xc=function(a){return a in pc?pc[a]:pc[a]="on"+a},Ac=function(a,b,c,e){var d=!0;if(a=vc(a))if(b=a.m[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var g=b[a];g&&g.capture==c&&!g.C&&(g=zc(g,e),d=d&&!1!==g)}return d},zc=function(a,b){var c=a.listener,e=a.S||a.src;if(a.O&&"number"!=typeof a&&a&&!a.C){var d=a.src;if(d&&d[ic])d.Ba(a);else{var g=a.type,f=a.I;d.removeEventListener?d.removeEventListener(g,f,a.capture):d.detachEvent?d.detachEvent(xc(g),f):d.addListener&&
d.removeListener&&d.removeListener(f);qc--;if(g=vc(d)){f=a.type;var h;if(h=f in g.m){h=g.m[f];var l=ea(h,a),m;if(m=0<=l)D(null!=h.length),Array.prototype.splice.call(h,l,1);h=m}h&&(lc(a),0==g.m[f].length&&(delete g.m[f],g.L--));0==g.L&&(g.src=null,d[oc]=null)}else lc(a)}}return c.call(e,b)},yc=function(a,b){if(a.C)return!0;if(!Vb){if(!b)a:{b=["window","event"];for(var c=u,e=0;e<b.length;e++)if(c=c[b[e]],null==c){b=null;break a}b=c}e=b;b=new X(e,this);c=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var d=
!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(f){d=!0}if(d||void 0==e.returnValue)e.returnValue=!0}e=[];for(d=b.currentTarget;d;d=d.parentNode)e.push(d);a=a.type;for(d=e.length-1;!b.U&&0<=d;d--){b.currentTarget=e[d];var g=Ac(e[d],a,!0,b);c=c&&g}for(d=0;!b.U&&d<e.length;d++)b.currentTarget=e[d],g=Ac(e[d],a,!1,b),c=c&&g}return c}return zc(a,new X(b,this))},vc=function(a){a=a[oc];return a instanceof mc?a:null},Bc="__closure_events_fn_"+(1E9*Math.random()>>>0),tc=function(a){D(a,"Listener can not be null.");
if("function"==y(a))return a;D(a.handleEvent,"An object listener must have handleEvent method.");a[Bc]||(a[Bc]=function(b){return a.handleEvent(b)});return a[Bc]};var Cc=function(){sc(Rb("enc-dec-btn"),"click",this.ta,!1,this)},Dc=["encodeDecode","Main"],Y=u;Dc[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+Dc[0]);for(var Z;Dc.length&&(Z=Dc.shift());)Dc.length||void 0===Cc?Y=Y[Z]&&Y[Z]!==Object.prototype[Z]?Y[Z]:Y[Z]={}:Y[Z]=Cc;var Ec=function(){var a=Sb();if(a=ha(a,function(a){return a.checked}))if(a=Qb(a))return a;throw Error(J("Please choose an encoding or decoding function."));};
Cc.prototype.ta=function(){var a=Rb("enc-dec-result"),b=Rb("enc-dec-error");Tb(b,"");Tb(a,"");try{var c=Ec(),e=Rb("enc-dec-input").value;if(!e)throw Error(J("Please do not leave this blank."));var d=Fc,g=(null!==d&&c in d?d[c]:void 0)(e);Tb(a,g)}catch(f){Tb(b,f)}};
var Fc={"base64-decode":function(a){try{var b=Qa(a);return Ka(b)}catch(c){throw Error(Ha());}},"base64-encode":function(a){return Oa(Ja(a),!1)},"base64url-encode":function(a){return Oa(Ja(a),!0).replace(/\.+$/,"")},"url-encode":function(a){return encodeURIComponent(String(a))},"url-decode":function(a){return decodeURIComponent(a.replace(/\+/g," "))},md5:function(a){var b=new L;b.update(Ja(a));a=b.digest();return Ia(a)},"saml-encode":function(a){a=new ib(Ja(a));var b,c=a.input;switch(a.P){case 0:var e=
0;for(b=c.length;e<b;){var d=O?c.subarray(e,e+65535):c.slice(e,e+65535);e+=d.length;var g=a;var f=e===b;var h=g.a,l=g.b;if(O){for(h=new Uint8Array(g.a.buffer);h.length<=l+d.length+5;)h=new Uint8Array(h.length<<1);h.set(g.a)}h[l++]=(f?1:0)|0;var m=d.length;f=~m+65536&65535;h[l++]=m&255;h[l++]=m>>>8&255;h[l++]=f&255;h[l++]=f>>>8&255;if(O)h.set(d,l),l+=d.length,h=h.subarray(0,l);else{m=0;for(f=d.length;m<f;++m)h[l++]=d[m];h.length=l}g.b=l;g.a=h}break;case 1:e=new P(O?new Uint8Array(a.a.buffer):a.a,a.b);
e.g(1,1,!0);e.g(1,2,!0);c=ob(a,c);b=0;for(g=c.length;b<g;b++)if(d=c[b],P.prototype.g.apply(e,jb[d]),256<d)e.g(c[++b],c[++b],!0),e.g(c[++b],5),e.g(c[++b],c[++b],!0);else if(256===d)break;e=e.finish();a.a=e;a.b=a.a.length;break;case 2:e=new P(O?new Uint8Array(a.a.buffer):a.a,a.b);var n,r=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15];l=Array(19);var k;e.g(1,1,!0);e.g(2,2,!0);c=ob(a,c);d=qb(a.pa,15);h=rb(d);b=qb(a.oa,7);g=rb(b);for(f=286;257<f&&0===d[f-1];f--);for(m=30;1<m&&0===b[m-1];m--);var q=f,
E=m;var t=new (O?Uint32Array:Array)(q+E);var B=new (O?Uint32Array:Array)(316),z;var w=new (O?Uint8Array:Array)(19);for(k=n=0;k<q;k++)t[n++]=d[k];for(k=0;k<E;k++)t[n++]=b[k];if(!O)for(k=0,E=w.length;k<E;++k)w[k]=0;k=z=0;for(E=t.length;k<E;k+=n){for(n=1;k+n<E&&t[k+n]===t[k];++n);q=n;if(0===t[k])if(3>q)for(;0<q--;)B[z++]=0,w[0]++;else for(;0<q;){var x=138>q?q:138;x>q-3&&x<q&&(x=q-3);10>=x?(B[z++]=17,B[z++]=x-3,w[17]++):(B[z++]=18,B[z++]=x-11,w[18]++);q-=x}else if(B[z++]=t[k],w[t[k]]++,q--,3>q)for(;0<
q--;)B[z++]=t[k],w[t[k]]++;else for(;0<q;)x=6>q?q:6,x>q-3&&x<q&&(x=q-3),B[z++]=16,B[z++]=x-3,w[16]++,q-=x}t=O?B.subarray(0,z):B.slice(0,z);w=qb(w,7);for(k=0;19>k;k++)l[k]=w[r[k]];for(n=19;4<n&&0===l[n-1];n--);r=rb(w);e.g(f-257,5,!0);e.g(m-1,5,!0);e.g(n-4,4,!0);for(k=0;k<n;k++)e.g(l[k],3,!0);k=0;for(l=t.length;k<l;k++)if(f=t[k],e.g(r[f],w[f],!0),16<=f){k++;switch(f){case 16:f=2;break;case 17:f=3;break;case 18:f=7;break;default:throw Error("invalid code: "+f);}e.g(t[k],f,!0)}d=[h,d];h=[g,b];b=d[0];
g=d[1];d=h[0];f=h[1];h=0;for(l=c.length;h<l;++h)if(m=c[h],e.g(b[m],g[m],!0),256<m)e.g(c[++h],c[++h],!0),m=c[++h],e.g(d[m],f[m],!0),e.g(c[++h],c[++h],!0);else if(256===m)break;e=e.finish();a.a=e;a.b=a.a.length;break;default:throw Error("invalid compression type");}return Oa(a.a)},"saml-decode":function(a){if(!a)return"";if(Nb.test(a))return a;var b=a;if(Ob.test(a)&&(b=decodeURIComponent(a.replace(/\+/g," ")),Nb.test(b)))return b;try{var c=Qa(b),e=Ka(c);if(Nb.test(e))return e}catch(q){throw Error(Ha());
}try{for(var d,g=new tb(c);!g.W;){c=b=a=void 0;e=g;var f=U(e,3);f&1&&(e.W=!0);f>>>=1;switch(f){case 0:var h=e.input,l=e.l,m=e.a,n=e.b,r=h.length,k=m.length;e.w=0;e.j=0;if(l+1>=r)throw Error("invalid uncompressed block header: LEN");c=h[l++]|h[l++]<<8;if(l+1>=r)throw Error("invalid uncompressed block header: NLEN");b=h[l++]|h[l++]<<8;if(c===~b)throw Error("invalid uncompressed block header: length verify");if(l+c>h.length)throw Error("input buffer is broken");switch(e.N){case 0:for(;n+c>m.length;){a=
k-n;c-=a;if(O)m.set(h.subarray(l,l+a),n),n+=a,l+=a;else for(;a--;)m[n++]=h[l++];e.b=n;m=e.o();n=e.b}break;case 1:for(;n+c>m.length;)m=e.o({Z:2});break;default:throw Error("invalid inflate mode");}if(O)m.set(h.subarray(l,l+c),n),n+=c,l+=c;else for(;c--;)m[n++]=h[l++];e.l=l;e.b=n;e.a=m;break;case 1:e.R(Eb,Hb);break;case 2:Mb(e);break;default:throw Error("unknown BTYPE: "+f);}}d=g.X()}catch(q){throw Error(J("Error doing the decompression."));}if(d=Ka(d))return d;throw Error(J("Unable to decode the encoded SAML message."));
},"pretty-json":function(a){var b=new $a;try{return b.format(a)}catch(c){throw Error(J("Not a valid JSON string."));}}};
